{ ... }:

{
  xdg.configFile."zed/themes/koppi-theme.json".text = ''
    {
      "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
      "name": "koppi-theme",
      "author": "koppi",
      "themes": [
        {
          "name": "koppi-theme",
          "appearance": "dark",
          "style": {
            "background":            "#1a1a1a",
            "elevated.surface":      "#252525",
            "surface":               "#252525",
            "panel.background":      "#1a1a1a",
            "border":                "#404040",
            "border.variant":        "#303030",
            "border.focused":        "#d4b048",
            "border.selected":       "#d4b048",
            "border.transparent":    "#00000000",
            "border.disabled":       "#303030",

            "text":                  "#e8e8e8",
            "text.muted":            "#909090",
            "text.placeholder":      "#525252",
            "text.disabled":         "#525252",
            "text.accent":           "#d4b048",

            "icon":                  "#e8e8e8",
            "icon.muted":            "#909090",
            "icon.disabled":         "#525252",
            "icon.placeholder":      "#525252",
            "icon.accent":           "#d4b048",

            "status_bar.background": "#1a1a1a",
            "title_bar.background":  "#1a1a1a",
            "toolbar.background":    "#252525",
            "tab_bar.background":    "#1a1a1a",
            "tab.inactive_background": "#1a1a1a",
            "tab.active_background": "#252525",

            "editor.background":              "#1a1a1a",
            "editor.gutter.background":       "#1a1a1a",
            "editor.subheader.background":    "#252525",
            "editor.active_line.background":  "#252525",
            "editor.highlighted_line.background": "#252525",
            "editor.line_number":             "#404040",
            "editor.active_line_number":      "#909090",
            "editor.invisible":               "#404040",
            "editor.wrap_guide":              "#252525",
            "editor.active_wrap_guide":       "#303030",
            "editor.indent_guide":            "#2e2e2e",
            "editor.indent_guide_active":     "#404040",
            "editor.foreground":              "#e8e8e8",
            "editor.document_highlight.read_background":  "#303030",
            "editor.document_highlight.write_background": "#404040",

            "scrollbar.thumb.background":       "#404040",
            "scrollbar.thumb.hover_background": "#525252",
            "scrollbar.thumb.border":           "#404040",
            "scrollbar.track.background":       "#1a1a1a",
            "scrollbar.track.border":           "#252525",

            "element.background":          "#252525",
            "element.hover":               "#303030",
            "element.active":              "#404040",
            "element.selected":            "#303030",
            "element.disabled":            "#252525",
            "drop_target.background":      "#303030",

            "ghost_element.background":    "#00000000",
            "ghost_element.hover":         "#252525",
            "ghost_element.active":        "#303030",
            "ghost_element.selected":      "#252525",
            "ghost_element.disabled":      "#525252",

            "link_text.hover":             "#e8c858",

            "selection.background":        "#40404066",
            "search.match_background":     "#8a702066",

            "terminal.background":         "#1a1a1a",
            "terminal.foreground":         "#e8e8e8",
            "terminal.bright_foreground":  "#f5f5f5",
            "terminal.dim_foreground":     "#909090",
            "terminal.ansi.black":         "#1a1a1a",
            "terminal.ansi.red":           "#b54a4a",
            "terminal.ansi.green":         "#5a8f6a",
            "terminal.ansi.yellow":        "#d4b048",
            "terminal.ansi.blue":          "#6b6b6b",
            "terminal.ansi.magenta":       "#4a4a4a",
            "terminal.ansi.cyan":          "#8a8a8a",
            "terminal.ansi.white":         "#e8e8e8",
            "terminal.ansi.bright_black":  "#404040",
            "terminal.ansi.bright_red":    "#c45a5a",
            "terminal.ansi.bright_green":  "#6aa07a",
            "terminal.ansi.bright_yellow": "#e8c858",
            "terminal.ansi.bright_blue":   "#909090",
            "terminal.ansi.bright_magenta":"#707070",
            "terminal.ansi.bright_cyan":   "#a8a8a8",
            "terminal.ansi.bright_white":  "#f5f5f5",

            "error":              "#b54a4a",
            "error.border":       "#b54a4a",
            "error.background":   "#b54a4a22",
            "warning":            "#c4924a",
            "warning.border":     "#c4924a",
            "warning.background": "#c4924a22",
            "info":               "#8a8a8a",
            "info.border":        "#8a8a8a",
            "success":            "#5a8f6a",
            "success.border":     "#5a8f6a",

            "hint":               "#707070",
            "predictive":         "#525252",

            "modified":           "#d4b048",
            "created":            "#5a8f6a",
            "deleted":            "#b54a4a",
            "conflict":           "#c4924a",
            "hidden":             "#707070",
            "ignored":            "#525252",
            "renamed":            "#d4b048",

            "players": [
              { "cursor": "#d4b048", "background": "#d4b04833", "selection": "#d4b04833" }
            ],

            "syntax": {
              "attribute":    { "color": "#707070" },
              "boolean":      { "color": "#d4b048", "font_style": "bold" },
              "comment":      { "color": "#6b6b6b", "font_style": "italic" },
              "comment.doc":  { "color": "#8a8a8a", "font_style": "italic" },
              "constant":     { "color": "#d4b048" },
              "constructor":  { "color": "#d4b048" },
              "embedded":     { "color": "#cdb87a" },
              "emphasis":     { "color": "#e8e8e8", "font_style": "italic" },
              "emphasis.strong": { "color": "#f5f5f5", "font_weight": 700 },
              "enum":         { "color": "#cdb87a" },
              "function":     { "color": "#f5f5f5" },
              "function.method": { "color": "#f5f5f5" },
              "function.builtin": { "color": "#909090" },
              "hint":         { "color": "#707070" },
              "keyword":      { "color": "#f5f5f5", "font_weight": 700 },
              "label":        { "color": "#cdb87a" },
              "link_text":    { "color": "#cdb87a" },
              "link_uri":     { "color": "#909090" },
              "number":       { "color": "#e8c858" },
              "operator":     { "color": "#e8e8e8" },
              "predictive":   { "color": "#525252", "font_style": "italic" },
              "preproc":      { "color": "#cdb87a" },
              "primary":      { "color": "#e8e8e8" },
              "property":     { "color": "#e8e8e8" },
              "punctuation":  { "color": "#707070" },
              "punctuation.bracket": { "color": "#707070" },
              "punctuation.delimiter": { "color": "#707070" },
              "punctuation.list_marker": { "color": "#d4b048" },
              "punctuation.special": { "color": "#909090" },
              "string":       { "color": "#cdb87a" },
              "string.escape": { "color": "#e8c858" },
              "string.regex": { "color": "#e8c858" },
              "string.special": { "color": "#e8c858" },
              "string.special.symbol": { "color": "#d4b048" },
              "tag":          { "color": "#d4b048" },
              "text.literal": { "color": "#d4b048" },
              "title":        { "color": "#f5f5f5", "font_weight": 700 },
              "type":         { "color": "#cdb87a" },
              "type.builtin": { "color": "#cdb87a" },
              "type.super":   { "color": "#cdb87a" },
              "variable":     { "color": "#e8e8e8" },
              "variable.builtin": { "color": "#cdb87a" },
              "variable.member": { "color": "#e8e8e8" },
              "variable.parameter": { "color": "#e8e8e8", "font_style": "italic" },
              "variant":      { "color": "#d4b048" }
            }
          }
        }
      ]
    }
  '';
}
