{ colors, ... }:

{
  xdg.configFile."zed/themes/koppi-theme.json".text = ''
    {
      "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
      "name": "koppi-theme",
      "author": "koppi",
      "themes": [
        {
          "name": "koppi-theme",
          "appearance": "dark",
          "style": {
            "background":            "#${colors.bg}",
            "elevated_surface.background": "#${colors.bg1}",
            "surface.background":    "#${colors.bg1}",
            "panel.background":      "#${colors.bg}",
            "border":                "#${colors.bg3}",
            "border.variant":        "#${colors.bg2}",
            "border.focused":        "#${colors.accent}",
            "border.selected":       "#${colors.accent}",
            "border.transparent":    "#${colors.transparent}",
            "border.disabled":       "#${colors.bgDim}",

            "accent":                "#${colors.accent}",

            "text":                  "#${colors.fg}",
            "text.muted":            "#${colors.fgMuted}",
            "text.placeholder":      "#${colors.bg4}",
            "text.disabled":         "#${colors.bg4}",
            "text.accent":           "#${colors.accent}",

            "icon":                  "#${colors.fg}",
            "icon.muted":            "#${colors.fgMuted}",
            "icon.disabled":         "#${colors.bg4}",
            "icon.placeholder":      "#${colors.bg4}",
            "icon.accent":           "#${colors.accent}",

            "status_bar.background": "#${colors.bg}",
            "title_bar.background":  "#${colors.bg}",
            "toolbar.background":    "#${colors.bg1}",
            "tab_bar.background":    "#${colors.bg}",
            "tab.inactive_background": "#${colors.bg}",
            "tab.active_background": "#${colors.bg1}",

            "editor.background":              "#${colors.bg}",
            "editor.gutter.background":       "#${colors.bg}",
            "editor.subheader.background":    "#${colors.bg1}",
            "editor.active_line.background":  "#${colors.bg1}",
            "editor.highlighted_line.background": "#${colors.bgLine}",
            "editor.line_number":             "#${colors.bgSelect}",
            "editor.active_line_number":      "#${colors.fgMuted}",
            "editor.invisible":               "#${colors.bgSelect}",
            "editor.wrap_guide":              "#${colors.bg1}",
            "editor.active_wrap_guide":       "#${colors.bg2}",
            "editor.indent_guide":            "#${colors.bgIndent}",
            "editor.indent_guide_active":     "#${colors.bg3}",
            "editor.foreground":              "#${colors.fg}",
            "editor.document_highlight.read_background":  "#${colors.bg2}",
            "editor.document_highlight.write_background": "#${colors.bgSelect}",

            "scrollbar.thumb.background":       "#${colors.bg3}",
            "scrollbar.thumb.hover_background": "#${colors.bg4}",
            "scrollbar.thumb.border":           "#${colors.bg3}",
            "scrollbar.track.background":       "#${colors.bg}",
            "scrollbar.track.border":           "#${colors.bg1}",

            "element.background":       "#${colors.bg1}",
            "element.hover":            "#${colors.bg2}",
            "element.active":           "#${colors.bgSelect}",
            "element.selected":         "#${colors.bg2}",
            "element.disabled":         "#${colors.bg1}",
            "drop_target.background":   "#${colors.bg2}",

            "ghost_element.background": "#${colors.transparent}",
            "ghost_element.hover":      "#${colors.bg1}",
            "ghost_element.active":     "#${colors.bg2}",
            "ghost_element.selected":   "#${colors.bg1}",
            "ghost_element.disabled":   "#${colors.bg4}",

            "link_text.hover":          "#${colors.acchigh}",

            "selection.background":     "#${colors.bgSelect}",
            "search.match_background":  "#${colors.accdim}55",

            "terminal.background":          "#${colors.bg}",
            "terminal.foreground":          "#${colors.fg}",
            "terminal.bright_foreground":   "#${colors.bwhite}",
            "terminal.dim_foreground":      "#${colors.fgMuted}",
            "terminal.ansi.black":          "#${colors.bg}",
            "terminal.ansi.red":            "#${colors.red}",
            "terminal.ansi.green":          "#${colors.green}",
            "terminal.ansi.yellow":         "#${colors.accent}",
            "terminal.ansi.blue":           "#${colors.bg4}",
            "terminal.ansi.magenta":        "#${colors.bg3}",
            "terminal.ansi.cyan":           "#${colors.fgMuted}",
            "terminal.ansi.white":          "#${colors.fg}",
            "terminal.ansi.bright_black":   "#${colors.bg3}",
            "terminal.ansi.bright_red":     "#${colors.bred}",
            "terminal.ansi.bright_green":   "#${colors.bgreen}",
            "terminal.ansi.bright_yellow":  "#${colors.accbrt}",
            "terminal.ansi.bright_blue":    "#${colors.fgMuted}",
            "terminal.ansi.bright_magenta": "#${colors.fg2}",
            "terminal.ansi.bright_cyan":    "#${colors.bcyan}",
            "terminal.ansi.bright_white":   "#${colors.bwhite}",

            "error":              "#${colors.bred}",
            "error.border":       "#${colors.bred}",
            "error.background":   "#${colors.bred}1a",
            "warning":            "#${colors.warning}",
            "warning.border":     "#${colors.warning}",
            "warning.background": "#${colors.warning}1a",
            "info":               "#${colors.fgMuted}",
            "info.border":        "#${colors.fgMuted}",
            "success":            "#${colors.bgreen}",
            "success.border":     "#${colors.bgreen}",

            "hint":               "#${colors.fg2}",
            "hint.background":    "#${colors.bg1}",
            "predictive":         "#${colors.bg4}",

            "modified":  "#${colors.accent}",
            "created":   "#${colors.bgreen}",
            "deleted":   "#${colors.bred}",
            "conflict":  "#${colors.warning}",
            "hidden":    "#${colors.fg2}",
            "ignored":   "#${colors.bg4}",
            "renamed":   "#${colors.accbrt}",

            "players": [
              { "cursor": "#${colors.accent}", "background": "#${colors.accent}30", "selection": "#${colors.accent}30" }
            ],

            "syntax": {
              "attribute":              { "color": "#${colors.fgSubtle}" },
              "boolean":                { "color": "#${colors.accbrt}", "font_weight": 700 },
              "comment":                { "color": "#${colors.fg2}" },
              "comment.doc":            { "color": "#${colors.fgMuted}" },
              "constant":               { "color": "#${colors.accbrt}" },
              "constructor":            { "color": "#${colors.accbrt}" },
              "embedded":               { "color": "#${colors.accent}" },
              "emphasis":               { "color": "#${colors.fg}" },
              "emphasis.strong":        { "color": "#${colors.bwhite}", "font_weight": 700 },
              "enum":                   { "color": "#${colors.accent}" },
              "function":               { "color": "#${colors.bwhite}" },
              "function.method":        { "color": "#${colors.bwhite}" },
              "function.builtin":       { "color": "#${colors.fgMuted}" },
              "hint":                   { "color": "#${colors.fg2}" },
              "keyword":                { "color": "#${colors.bwhite}", "font_weight": 700 },
              "label":                  { "color": "#${colors.accent}" },
              "link_text":              { "color": "#${colors.accent}" },
              "link_uri":               { "color": "#${colors.fgMuted}" },
              "number":                 { "color": "#${colors.acchigh}" },
              "operator":               { "color": "#${colors.fg}" },
              "predictive":             { "color": "#${colors.bg4}" },
              "preproc":                { "color": "#${colors.accent}" },
              "primary":                { "color": "#${colors.fg}" },
              "property":               { "color": "#${colors.fg}" },
              "punctuation":            { "color": "#${colors.fgSubtle}" },
              "punctuation.bracket":    { "color": "#${colors.fgSubtle}" },
              "punctuation.delimiter":  { "color": "#${colors.fgSubtle}" },
              "punctuation.list_marker":{ "color": "#${colors.accent}" },
              "punctuation.special":    { "color": "#${colors.fgMuted}" },
              "string":                 { "color": "#${colors.accent}" },
              "string.escape":          { "color": "#${colors.acchigh}" },
              "string.regex":           { "color": "#${colors.acchigh}" },
              "string.special":         { "color": "#${colors.acchigh}" },
              "string.special.symbol":  { "color": "#${colors.accbrt}" },
              "tag":                    { "color": "#${colors.accbrt}" },
              "text.literal":           { "color": "#${colors.accbrt}" },
              "title":                  { "color": "#${colors.bwhite}", "font_weight": 700 },
              "type":                   { "color": "#${colors.accent}" },
              "type.builtin":           { "color": "#${colors.accent}" },
              "type.super":             { "color": "#${colors.accent}" },
              "variable":               { "color": "#${colors.fg}" },
              "variable.builtin":       { "color": "#${colors.accent}" },
              "variable.member":        { "color": "#${colors.fg}" },
              "variable.parameter":     { "color": "#${colors.fg}" },
              "variant":                { "color": "#${colors.accbrt}" }
            }
          }
        }
      ]
    }
  '';
}
